// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v7.35.1
// source: support.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "support";

/**
 * The first client frame must authenticate. Later frames only keep the
 * connection alive; durable ticket mutations stay on the HTTP API.
 */
export interface ClientMessage {
  /** auth | ping */
  type: string;
  token: string;
  anonymousToken: string;
  body: string;
  actionId: string;
}

export interface TicketEvent {
  ticketId: string;
  status: string;
  escalationLevel: string;
  authorType: string;
  body: string;
  createdAt: string;
}

export interface ServerMessage {
  /** connected | ticket_updated | message | internal_note | pong | error */
  type: string;
  code: string;
  actionId: string;
  event?: TicketEvent | undefined;
}

function createBaseClientMessage(): ClientMessage {
  return { type: "", token: "", anonymousToken: "", body: "", actionId: "" };
}

export const ClientMessage: MessageFns<ClientMessage> = {
  encode(message: ClientMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.token !== "") {
      writer.uint32(18).string(message.token);
    }
    if (message.anonymousToken !== "") {
      writer.uint32(26).string(message.anonymousToken);
    }
    if (message.body !== "") {
      writer.uint32(34).string(message.body);
    }
    if (message.actionId !== "") {
      writer.uint32(42).string(message.actionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClientMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseClientMessage();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.type = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.token = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.anonymousToken = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.body = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.actionId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ClientMessage {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      anonymousToken: isSet(object.anonymousToken)
        ? globalThis.String(object.anonymousToken)
        : isSet(object.anonymous_token)
        ? globalThis.String(object.anonymous_token)
        : "",
      body: isSet(object.body) ? globalThis.String(object.body) : "",
      actionId: isSet(object.actionId)
        ? globalThis.String(object.actionId)
        : isSet(object.action_id)
        ? globalThis.String(object.action_id)
        : "",
    };
  },

  toJSON(message: ClientMessage): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.anonymousToken !== "") {
      obj.anonymousToken = message.anonymousToken;
    }
    if (message.body !== "") {
      obj.body = message.body;
    }
    if (message.actionId !== "") {
      obj.actionId = message.actionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ClientMessage>, I>>(base?: I): ClientMessage {
    return ClientMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClientMessage>, I>>(object: I): ClientMessage {
    const message = createBaseClientMessage();
    message.type = object.type ?? "";
    message.token = object.token ?? "";
    message.anonymousToken = object.anonymousToken ?? "";
    message.body = object.body ?? "";
    message.actionId = object.actionId ?? "";
    return message;
  },
};

function createBaseTicketEvent(): TicketEvent {
  return { ticketId: "", status: "", escalationLevel: "", authorType: "", body: "", createdAt: "" };
}

export const TicketEvent: MessageFns<TicketEvent> = {
  encode(message: TicketEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ticketId !== "") {
      writer.uint32(10).string(message.ticketId);
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    if (message.escalationLevel !== "") {
      writer.uint32(26).string(message.escalationLevel);
    }
    if (message.authorType !== "") {
      writer.uint32(34).string(message.authorType);
    }
    if (message.body !== "") {
      writer.uint32(42).string(message.body);
    }
    if (message.createdAt !== "") {
      writer.uint32(50).string(message.createdAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TicketEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTicketEvent();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.ticketId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.status = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.escalationLevel = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.authorType = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.body = reader.string();
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.createdAt = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): TicketEvent {
    return {
      ticketId: isSet(object.ticketId)
        ? globalThis.String(object.ticketId)
        : isSet(object.ticket_id)
        ? globalThis.String(object.ticket_id)
        : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      escalationLevel: isSet(object.escalationLevel)
        ? globalThis.String(object.escalationLevel)
        : isSet(object.escalation_level)
        ? globalThis.String(object.escalation_level)
        : "",
      authorType: isSet(object.authorType)
        ? globalThis.String(object.authorType)
        : isSet(object.author_type)
        ? globalThis.String(object.author_type)
        : "",
      body: isSet(object.body) ? globalThis.String(object.body) : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "",
    };
  },

  toJSON(message: TicketEvent): unknown {
    const obj: any = {};
    if (message.ticketId !== "") {
      obj.ticketId = message.ticketId;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.escalationLevel !== "") {
      obj.escalationLevel = message.escalationLevel;
    }
    if (message.authorType !== "") {
      obj.authorType = message.authorType;
    }
    if (message.body !== "") {
      obj.body = message.body;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TicketEvent>, I>>(base?: I): TicketEvent {
    return TicketEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TicketEvent>, I>>(object: I): TicketEvent {
    const message = createBaseTicketEvent();
    message.ticketId = object.ticketId ?? "";
    message.status = object.status ?? "";
    message.escalationLevel = object.escalationLevel ?? "";
    message.authorType = object.authorType ?? "";
    message.body = object.body ?? "";
    message.createdAt = object.createdAt ?? "";
    return message;
  },
};

function createBaseServerMessage(): ServerMessage {
  return { type: "", code: "", actionId: "", event: undefined };
}

export const ServerMessage: MessageFns<ServerMessage> = {
  encode(message: ServerMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.code !== "") {
      writer.uint32(18).string(message.code);
    }
    if (message.actionId !== "") {
      writer.uint32(26).string(message.actionId);
    }
    if (message.event !== undefined) {
      TicketEvent.encode(message.event, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseServerMessage();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.type = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.code = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.actionId = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.event = TicketEvent.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ServerMessage {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      actionId: isSet(object.actionId)
        ? globalThis.String(object.actionId)
        : isSet(object.action_id)
        ? globalThis.String(object.action_id)
        : "",
      event: isSet(object.event) ? TicketEvent.fromJSON(object.event) : undefined,
    };
  },

  toJSON(message: ServerMessage): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.actionId !== "") {
      obj.actionId = message.actionId;
    }
    if (message.event !== undefined) {
      obj.event = TicketEvent.toJSON(message.event);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerMessage>, I>>(base?: I): ServerMessage {
    return ServerMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerMessage>, I>>(object: I): ServerMessage {
    const message = createBaseServerMessage();
    message.type = object.type ?? "";
    message.code = object.code ?? "";
    message.actionId = object.actionId ?? "";
    message.event = (object.event !== undefined && object.event !== null)
      ? TicketEvent.fromPartial(object.event)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
