// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/support.proto

package supportproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The first client frame must authenticate. Later frames only keep the
// connection alive; durable ticket mutations stay on the HTTP API.
type ClientMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // auth | ping
	Token          string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	AnonymousToken string                 `protobuf:"bytes,3,opt,name=anonymous_token,json=anonymousToken,proto3" json:"anonymous_token,omitempty"`
	Body           string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	ActionId       string                 `protobuf:"bytes,5,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_proto_support_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_support_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_proto_support_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClientMessage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ClientMessage) GetAnonymousToken() string {
	if x != nil {
		return x.AnonymousToken
	}
	return ""
}

func (x *ClientMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ClientMessage) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

type TicketEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TicketId        string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	EscalationLevel string                 `protobuf:"bytes,3,opt,name=escalation_level,json=escalationLevel,proto3" json:"escalation_level,omitempty"`
	AuthorType      string                 `protobuf:"bytes,4,opt,name=author_type,json=authorType,proto3" json:"author_type,omitempty"`
	Body            string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TicketEvent) Reset() {
	*x = TicketEvent{}
	mi := &file_proto_support_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketEvent) ProtoMessage() {}

func (x *TicketEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_support_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketEvent.ProtoReflect.Descriptor instead.
func (*TicketEvent) Descriptor() ([]byte, []int) {
	return file_proto_support_proto_rawDescGZIP(), []int{1}
}

func (x *TicketEvent) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *TicketEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TicketEvent) GetEscalationLevel() string {
	if x != nil {
		return x.EscalationLevel
	}
	return ""
}

func (x *TicketEvent) GetAuthorType() string {
	if x != nil {
		return x.AuthorType
	}
	return ""
}

func (x *TicketEvent) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *TicketEvent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ServerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // connected | ticket_updated | message | internal_note | pong | error
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	ActionId      string                 `protobuf:"bytes,3,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Event         *TicketEvent           `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_support_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_support_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_support_proto_rawDescGZIP(), []int{2}
}

func (x *ServerMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServerMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ServerMessage) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ServerMessage) GetEvent() *TicketEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_proto_support_proto protoreflect.FileDescriptor

const file_proto_support_proto_rawDesc = "" +
	"\n" +
	"\x13proto/support.proto\x12\asupport\"\x93\x01\n" +
	"\rClientMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12'\n" +
	"\x0fanonymous_token\x18\x03 \x01(\tR\x0eanonymousToken\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1b\n" +
	"\taction_id\x18\x05 \x01(\tR\bactionId\"\xc1\x01\n" +
	"\vTicketEvent\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12)\n" +
	"\x10escalation_level\x18\x03 \x01(\tR\x0fescalationLevel\x12\x1f\n" +
	"\vauthor_type\x18\x04 \x01(\tR\n" +
	"authorType\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\x80\x01\n" +
	"\rServerMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1b\n" +
	"\taction_id\x18\x03 \x01(\tR\bactionId\x12*\n" +
	"\x05event\x18\x04 \x01(\v2\x14.support.TicketEventR\x05eventB;Z9gopkg.aoctech.app/account/api/internal/proto;supportprotob\x06proto3"

var (
	file_proto_support_proto_rawDescOnce sync.Once
	file_proto_support_proto_rawDescData []byte
)

func file_proto_support_proto_rawDescGZIP() []byte {
	file_proto_support_proto_rawDescOnce.Do(func() {
		file_proto_support_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_support_proto_rawDesc), len(file_proto_support_proto_rawDesc)))
	})
	return file_proto_support_proto_rawDescData
}

var file_proto_support_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_support_proto_goTypes = []any{
	(*ClientMessage)(nil), // 0: support.ClientMessage
	(*TicketEvent)(nil),   // 1: support.TicketEvent
	(*ServerMessage)(nil), // 2: support.ServerMessage
}
var file_proto_support_proto_depIdxs = []int32{
	1, // 0: support.ServerMessage.event:type_name -> support.TicketEvent
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_support_proto_init() }
func file_proto_support_proto_init() {
	if File_proto_support_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_support_proto_rawDesc), len(file_proto_support_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_support_proto_goTypes,
		DependencyIndexes: file_proto_support_proto_depIdxs,
		MessageInfos:      file_proto_support_proto_msgTypes,
	}.Build()
	File_proto_support_proto = out.File
	file_proto_support_proto_goTypes = nil
	file_proto_support_proto_depIdxs = nil
}
